repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ['--ignore', 'F401', '--exclude', '.*\\.pyi']
      - id: ruff-format
        exclude: '.*\\.pyi'

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: .venv/bin/pytest
        language: system
        pass_filenames: false