from typing import Any, Dict, Optional, Tuple

# Algorithm constants
HS256: str
HS384: str
HS512: str
RS256: str
RS384: str
RS512: str
ES256: str
ES384: str
PS256: str
PS384: str
PS512: str
EDDSA: str

# JWT module constants
JWT_TOKEN_ACCESS: str
JWT_TOKEN_REFRESH: str

# JWT functions
def access(token_instance: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
def refresh(token_instance: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
def rotation(token_instance: Any, refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...
async def access_async(token_instance: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
async def refresh_async(token_instance: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
async def rotation_async(token_instance: Any, refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...

# Secret functions
def secret_key() -> str: ...
def secret_key_with_size(size: int) -> str: ...
def generate_hmac_secret(size: int) -> str: ...
async def generate_hmac_secret_async(size: int) -> str: ...
def generate_rsa_keypair(bits: Optional[int] = None) -> Tuple[str, str]: ...

# Time functions
def now() -> int: ...
def seconds(n: int) -> int: ...
def minutes(n: int) -> int: ...
def hours(n: int) -> int: ...
def days(n: int) -> int: ...
def weeks(n: int) -> int: ...

# Utils constants
DEFAULT_SECRET_SIZE: int
MIN_SECRET_SIZE: int
TOKEN_ACCESS: str
TOKEN_REFRESH: str

# JWT format functions
def is_jwt_format(token: str) -> bool: ...
def validate_jwt_format(token: str) -> bool: ...

# CipherToken class with full autocomplete support
class CipherToken:
    def __init__(self, secret: str, algorithm: str, access_ttl: int, refresh_ttl: int) -> None: ...
    
    # Token creation
    def create_token(self,ttl_time: int, token_type: str, payload: Optional[Dict[str, Any]] = None) -> str: ...
    def access(self,payload: Optional[Dict[str, Any]] = None) -> str: ...
    def refresh(self,payload: Optional[Dict[str, Any]] = None) -> str: ...
    
    # Token inspection/decoding
    def decode(self,token: str) -> Dict[str, Any]: ...
    def verify(self,token: str) -> bool: ...
    def inspect(self,token: str) -> Dict[str, Any]: ...
    
    # Token rotation
    def rotation(self,refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...
    
    # Utility methods
    def remaining_time(self,token: str) -> Optional[int]: ...
    def algorithm_name(self,) -> str: ...
    
    # Properties
    @property
    def secret(self) -> str: ...
    @property
    def access_ttl(self) -> int: ...
    @property
    def refresh_ttl(self) -> int: ...
    
    # Async methods
    async def access_async(self,payload: Optional[Dict[str, Any]] = None) -> str: ...
    async def refresh_async(self,payload: Optional[Dict[str, Any]] = None) -> str: ...
    async def decode_async(self,token: str) -> Dict[str, Any]: ...
    async def verify_async(self,token: str) -> bool: ...
    async def rotation_async(self,refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...