from typing import Any, Dict, Optional, Tuple

def access(token: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
def refresh(token: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
def rotation(
    token: Any, refresh_token: str, payload: Optional[Dict[str, Any]] = None
) -> Tuple[str, str]: ...

async def access_async(token: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
async def refresh_async(token: Any, payload: Optional[Dict[str, Any]] = None) -> str: ...
async def rotation_async(
    token: Any, refresh_token: str, payload: Optional[Dict[str, Any]] = None
) -> Tuple[str, str]: ...

TOKEN_ACCESS: str
TOKEN_REFRESH: str