from typing import Tuple

def secret_key() -> str: ...
def secret_key_with_size(size: int) -> str: ...
def generate_hmac_secret(size: int) -> str: ...
async def generate_hmac_secret_async(size: int) -> str: ...
def generate_rsa_keypair(bits: int = ...) -> Tuple[str, str]: ...